name: XPSpack CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - beta
    paths:
      - 'packages/XPSpack/src/**'
      - 'packages/XPSpack/test/**'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3' # Replace this with the minimum Julia version that your package supports. E.g. if your package requires Julia 1.5 or higher, change this to '1.5'.
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
        - uses: actions/checkout@v3
        - run: julia -e 'using Pkg; Pkg.add(url="https://github.com/matthewozon/NMOpt"); Pkg.build("NMopt"); using NMOpt; Pkg.activate("packages/XPSpack/"); Pkg.build("XPSpack")' #; Pkg.test("XPSpack"; coverage=true)'
